db:
    image: mongo
    volumes: 
        - /data/db:/data/db
redis:
    image: redis
lochat-base:
    build: .
    env_file: set_envs.env
    command: python3.4 manage.py runserver --host 0.0.0.0
    volumes: 
        - .:/usr/src/app
    ports:
        - "5000:5000"
    links:
        - db
        - redis

